#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OSCinator(object):
    def setupUi(self, OSCinator):
        OSCinator.setObjectName("OSCinator")
        OSCinator.resize(775, 319)
        self.centralwidget = QtWidgets.QWidget(OSCinator)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 50, 64, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 64, 17))
        self.label_2.setObjectName("label_2")
        self.port = QtWidgets.QSpinBox(self.centralwidget)
        self.port.setGeometry(QtCore.QRect(60, 40, 71, 26))
        self.port.setMaximum(65000)
        self.port.setProperty("value", 9000)
        self.port.setObjectName("port")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(280, 20, 491, 41))
        self.label_5.setObjectName("label_5")
        self.verticalSlider = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider.setGeometry(QtCore.QRect(330, 79, 20, 181))
        self.verticalSlider.setMaximum(127)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(40, 70, 51, 41))
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 180, 51, 41))
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(190, 70, 51, 41))
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(190, 184, 51, 41))
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.slide = QtWidgets.QLineEdit(self.centralwidget)
        self.slide.setGeometry(QtCore.QRect(280, 260, 113, 25))
        self.slide.setObjectName("slide")
        self.slide2 = QtWidgets.QLineEdit(self.centralwidget)
        self.slide2.setGeometry(QtCore.QRect(400, 260, 113, 25))
        self.slide2.setObjectName("slide2")
        self.slide3 = QtWidgets.QLineEdit(self.centralwidget)
        self.slide3.setGeometry(QtCore.QRect(520, 260, 113, 25))
        self.slide3.setObjectName("slide3")
        self.slide4 = QtWidgets.QLineEdit(self.centralwidget)
        self.slide4.setGeometry(QtCore.QRect(640, 260, 113, 25))
        self.slide4.setObjectName("slide4")
        self.verticalSlider_2 = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider_2.setGeometry(QtCore.QRect(450, 79, 20, 181))
        self.verticalSlider_2.setMaximum(127)
        self.verticalSlider_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_2.setObjectName("verticalSlider_2")
        self.verticalSlider_3 = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider_3.setGeometry(QtCore.QRect(570, 79, 20, 181))
        self.verticalSlider_3.setMaximum(127)
        self.verticalSlider_3.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_3.setObjectName("verticalSlider_3")
        self.verticalSlider_4 = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider_4.setGeometry(QtCore.QRect(690, 79, 20, 181))
        self.verticalSlider_4.setMaximum(127)
        self.verticalSlider_4.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_4.setObjectName("verticalSlider_4")
        self.push = QtWidgets.QLineEdit(self.centralwidget)
        self.push.setGeometry(QtCore.QRect(10, 120, 113, 25))
        self.push.setObjectName("push")
        self.release = QtWidgets.QLineEdit(self.centralwidget)
        self.release.setGeometry(QtCore.QRect(10, 150, 113, 25))
        self.release.setObjectName("release")
        self.push3 = QtWidgets.QLineEdit(self.centralwidget)
        self.push3.setGeometry(QtCore.QRect(160, 120, 113, 25))
        self.push3.setObjectName("push3")
        self.release2 = QtWidgets.QLineEdit(self.centralwidget)
        self.release2.setGeometry(QtCore.QRect(10, 260, 113, 25))
        self.release2.setObjectName("release2")
        self.push2 = QtWidgets.QLineEdit(self.centralwidget)
        self.push2.setGeometry(QtCore.QRect(10, 230, 113, 25))
        self.push2.setObjectName("push2")
        self.release3 = QtWidgets.QLineEdit(self.centralwidget)
        self.release3.setGeometry(QtCore.QRect(160, 150, 113, 25))
        self.release3.setObjectName("release3")
        self.push4 = QtWidgets.QLineEdit(self.centralwidget)
        self.push4.setGeometry(QtCore.QRect(160, 230, 113, 25))
        self.push4.setObjectName("push4")
        self.release4 = QtWidgets.QLineEdit(self.centralwidget)
        self.release4.setGeometry(QtCore.QRect(160, 260, 113, 25))
        self.release4.setObjectName("release4")
        self.url = QtWidgets.QLineEdit(self.centralwidget)
        self.url.setGeometry(QtCore.QRect(60, 10, 191, 25))
        self.url.setObjectName("url")
        OSCinator.setCentralWidget(self.centralwidget)

        self.retranslateUi(OSCinator)
        QtCore.QMetaObject.connectSlotsByName(OSCinator)

    def retranslateUi(self, OSCinator):
        _translate = QtCore.QCoreApplication.translate
        OSCinator.setWindowTitle(_translate("OSCinator", "OSCinator"))
        self.label.setText(_translate("OSCinator", "Port"))
        self.label_2.setText(_translate("OSCinator", "URL"))
        self.label_5.setText(_translate("OSCinator", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:600; font-style:italic;\">The infamous OSCinator!</span></p></body></html>"))
        self.slide.setToolTip(_translate("OSCinator", "path to send when changed"))
        self.slide.setText(_translate("OSCinator", "/midi/cc1"))
        self.slide2.setToolTip(_translate("OSCinator", "path to send when changed"))
        self.slide2.setText(_translate("OSCinator", "/midi/cc2"))
        self.slide3.setToolTip(_translate("OSCinator", "path to send when changed"))
        self.slide3.setText(_translate("OSCinator", "/midi/cc3"))
        self.slide4.setToolTip(_translate("OSCinator", "path to send when changed"))
        self.slide4.setText(_translate("OSCinator", "/midi/cc4"))
        self.push.setToolTip(_translate("OSCinator", "path to send when clicked"))
        self.push.setText(_translate("OSCinator", "/midi/noteon36"))
        self.release.setToolTip(_translate("OSCinator", "path to send when released"))
        self.release.setText(_translate("OSCinator", "/midi/noteoff36"))
        self.push3.setToolTip(_translate("OSCinator", "path to send when clicked"))
        self.push3.setText(_translate("OSCinator", "/midi/noteon38"))
        self.release2.setToolTip(_translate("OSCinator", "path to send when released"))
        self.release2.setText(_translate("OSCinator", "/midi/noteoff42"))
        self.push2.setToolTip(_translate("OSCinator", "path to send when clicked"))
        self.push2.setText(_translate("OSCinator", "/midi/noteon42"))
        self.release3.setToolTip(_translate("OSCinator", "path to send when released"))
        self.release3.setText(_translate("OSCinator", "/midi/noteoff38"))
        self.push4.setToolTip(_translate("OSCinator", "path to send when clicked"))
        self.push4.setText(_translate("OSCinator", "/midi/noteon56"))
        self.release4.setToolTip(_translate("OSCinator", "path to send when released"))
        self.release4.setText(_translate("OSCinator", "/midi/noteoff56"))
        self.url.setText(_translate("OSCinator", "127.0.0.1"))


if __name__ == "__main__":
    import cb
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OSCinator = QtWidgets.QMainWindow()
    ui = Ui_OSCinator()
    ui.setupUi(OSCinator)
    cb.setup(ui)
    OSCinator.show()
    sys.exit(app.exec_())
